### PR TITLE
Update to 9.2

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- Fix dependency pins, which should make the config added in PR #12 unnnecessary.
- That option blocked the migration of this package to Python 3.12.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge/core, how can we manually request a migration of this package to Python 3.12?

I thought the changes done in this PR should fix the problem encountered by the bot, but it still hasn't generated an automatic PR.

**Comment by mbargull** [comment]
https://conda-forge.org/status/#python312 shows:
```
                osx_arm64_python3.8.____cpython: Could not solve for environment specs
The following packages are incompatible
├─ pyobjc-core 9.2.*  is installable with the potential options
│  ├─ pyobjc-core 9.2 would require
│  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  ├─ pyobjc-core 9.2 would require
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ pyobjc-core 9.2 would require
│  │  └─ python_abi 3.12.* *_cp312, which can be installed;
│  └─ pyobjc-core 9.2 would require
│     └─ python_abi 3.9.* *_cp39, which can be installed;
├─ pyobjc-framework-fsevents 9.2.*  is installable with the potential options
│  ├─ pyobjc-framework-fsevents 9.2 would require
│  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  ├─ pyobjc-framework-fsevents 9.2 would require
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ pyobjc-framework-fsevents 9.2 would require
│  │  └─ python_abi 3.12.* *_cp312, which can be installed;
│  └─ pyobjc-framework-fsevents 9.2 would require
│     └─ python_abi 3.9.* *_cp39, which can be installed;
├─ python >=3.8,<3.9.0a0  is not installable because it requires
│  └─ python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
└─ python_abi 3.8.* *_cp38 is not installable because it conflicts with any installable versions previously reported.
```
which means no `python=3.8` builds for the dependencies are available on `osx-arm64`.
Since the `osx-arm64` builds still happen on `osx-64`, we don't test the built packages on the CI => `conda-forge::pyobjc-framework-coreservices[subdir=osx-arm64]` builds for `python=3.8` are created but should actually be defunct/non-installable.

You should add an additional condition to the selector for `skip`; see https://github.com/conda-forge/pyobjc-core-feedstock/pull/35 .
If that is done, the migration PR will be created at some point.

**Comment by ccordoba12** [comment]
Thanks for your help @mbargull!

**Pull request merged**
