### PR TITLE
MAINT: Bump to 10.3

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

No idea why this one didn't autotick to 10.3 then 10.3.1, but this takes care of the first one. Will open a PR for 10.3.1 next.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
@conda-forge-admin, please restart ci

**Comment by larsoner** [comment]
@conda-forge-admin, please restart ci

**Comment by larsoner** [comment]
Okay all green, should be good to go! Once it's in I'll open a PR for 10.3.1

**Comment by ccordoba12** [comment]
Thanks @larsoner for your help with this!

**Pull request merged**
